### ISSUE TITLE
Post-release todo list

### ISSUE THREAD

**Issue by stevenpenavajr** [stevenpenavajr/skate#42]
- [ ] Come up with email reply format

- [x] Fix video playing inconsistently and make a fallback UI

- [ ] Images bigger on mobile + desktop (might need different pics)

- [ ] Auto slideshow stop
